services:
  postgres:
    image: postgres:18
    ports:
      - "5432:5432"
    volumes:
      - relay_postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=relay
      - POSTGRES_USER=relay
      - POSTGRES_DB=relay

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.0
    command:
      - start-dev
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: http://localhost:8081
      KC_HOSTNAME_ADMIN_URL: http://localhost:8081
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HTTP_RELATIVE_PATH: /
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USE_DATABASE: keycloak
      KC_DB_PASSWORD: relay
      KC_DB_USERNAME: relay
      KC_DB_SCHEMA: public
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live' ]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:8.4.0
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  relay_postgres_data:
    driver: local
  cache:
    driver: local

